export const metadata = {
  title: "Timeline",
  description: "Generated by create next app",
};

const TimelinePage = () => {
  return (
    <div className='text-center text-5xl text-blue-400'>
      Timeline Page
    </div>
  );
};

export default TimelinePage;